// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// cpp_vienna_cudaMatrix_saxpy
SEXP cpp_vienna_cudaMatrix_saxpy(SEXP alpha_, SEXP A_, SEXP B_);
RcppExport SEXP gpuRcuda_cpp_vienna_cudaMatrix_saxpy(SEXP alpha_SEXP, SEXP A_SEXP, SEXP B_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type alpha_(alpha_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type A_(A_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type B_(B_SEXP);
    __result = Rcpp::wrap(cpp_vienna_cudaMatrix_saxpy(alpha_, A_, B_));
    return __result;
END_RCPP
}
// cpp_vienna_cudaMatrix_daxpy
SEXP cpp_vienna_cudaMatrix_daxpy(SEXP alpha_, SEXP A_, SEXP B_);
RcppExport SEXP gpuRcuda_cpp_vienna_cudaMatrix_daxpy(SEXP alpha_SEXP, SEXP A_SEXP, SEXP B_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type alpha_(alpha_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type A_(A_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type B_(B_SEXP);
    __result = Rcpp::wrap(cpp_vienna_cudaMatrix_daxpy(alpha_, A_, B_));
    return __result;
END_RCPP
}
// cpp_vienna_cudaMatrix_sgemm
SEXP cpp_vienna_cudaMatrix_sgemm(SEXP A_, SEXP B_);
RcppExport SEXP gpuRcuda_cpp_vienna_cudaMatrix_sgemm(SEXP A_SEXP, SEXP B_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type A_(A_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type B_(B_SEXP);
    __result = Rcpp::wrap(cpp_vienna_cudaMatrix_sgemm(A_, B_));
    return __result;
END_RCPP
}
// cpp_vienna_cudaMatrix_dgemm
SEXP cpp_vienna_cudaMatrix_dgemm(SEXP A_, SEXP B_);
RcppExport SEXP gpuRcuda_cpp_vienna_cudaMatrix_dgemm(SEXP A_SEXP, SEXP B_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type A_(A_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type B_(B_SEXP);
    __result = Rcpp::wrap(cpp_vienna_cudaMatrix_dgemm(A_, B_));
    return __result;
END_RCPP
}
