# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_vienna_cudaMatrix_sgemm <- function(A_, B_) {
    .Call('gpuRcuda_cpp_vienna_cudaMatrix_sgemm', PACKAGE = 'gpuRcuda', A_, B_)
}

cpp_vienna_cudaMatrix_dgemm <- function(A_, B_) {
    .Call('gpuRcuda_cpp_vienna_cudaMatrix_dgemm', PACKAGE = 'gpuRcuda', A_, B_)
}

