# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vectorToIntXptr <- function(data) {
    .Call('gpuRcuda_vectorToIntXptr', PACKAGE = 'gpuRcuda', data)
}

vectorToFloatXptr <- function(data) {
    .Call('gpuRcuda_vectorToFloatXptr', PACKAGE = 'gpuRcuda', data)
}

vectorToDoubleXptr <- function(data) {
    .Call('gpuRcuda_vectorToDoubleXptr', PACKAGE = 'gpuRcuda', data)
}

matrixToIntXptr <- function(data) {
    .Call('gpuRcuda_matrixToIntXptr', PACKAGE = 'gpuRcuda', data)
}

matrixToFloatXptr <- function(data) {
    .Call('gpuRcuda_matrixToFloatXptr', PACKAGE = 'gpuRcuda', data)
}

matrixToDoubleXptr <- function(data) {
    .Call('gpuRcuda_matrixToDoubleXptr', PACKAGE = 'gpuRcuda', data)
}

dXptrToVecSEXP <- function(ptrA) {
    .Call('gpuRcuda_dXptrToVecSEXP', PACKAGE = 'gpuRcuda', ptrA)
}

fXptrToVecSEXP <- function(ptrA) {
    .Call('gpuRcuda_fXptrToVecSEXP', PACKAGE = 'gpuRcuda', ptrA)
}

iXptrToVecSEXP <- function(ptrA) {
    .Call('gpuRcuda_iXptrToVecSEXP', PACKAGE = 'gpuRcuda', ptrA)
}

dXptrToSEXP <- function(ptrA) {
    .Call('gpuRcuda_dXptrToSEXP', PACKAGE = 'gpuRcuda', ptrA)
}

fXptrToSEXP <- function(ptrA) {
    .Call('gpuRcuda_fXptrToSEXP', PACKAGE = 'gpuRcuda', ptrA)
}

iXptrToSEXP <- function(ptrA) {
    .Call('gpuRcuda_iXptrToSEXP', PACKAGE = 'gpuRcuda', ptrA)
}

emptyVecIntXptr <- function(size) {
    .Call('gpuRcuda_emptyVecIntXptr', PACKAGE = 'gpuRcuda', size)
}

emptyVecFloatXptr <- function(size) {
    .Call('gpuRcuda_emptyVecFloatXptr', PACKAGE = 'gpuRcuda', size)
}

emptyVecDoubleXptr <- function(size) {
    .Call('gpuRcuda_emptyVecDoubleXptr', PACKAGE = 'gpuRcuda', size)
}

emptyIntXptr <- function(nr, nc) {
    .Call('gpuRcuda_emptyIntXptr', PACKAGE = 'gpuRcuda', nr, nc)
}

emptyFloatXptr <- function(nr, nc) {
    .Call('gpuRcuda_emptyFloatXptr', PACKAGE = 'gpuRcuda', nr, nc)
}

emptyDoubleXptr <- function(nr, nc) {
    .Call('gpuRcuda_emptyDoubleXptr', PACKAGE = 'gpuRcuda', nr, nc)
}

cpp_dncol <- function(ptrA) {
    .Call('gpuRcuda_cpp_dncol', PACKAGE = 'gpuRcuda', ptrA)
}

cpp_fncol <- function(ptrA) {
    .Call('gpuRcuda_cpp_fncol', PACKAGE = 'gpuRcuda', ptrA)
}

cpp_incol <- function(ptrA) {
    .Call('gpuRcuda_cpp_incol', PACKAGE = 'gpuRcuda', ptrA)
}

cpp_dnrow <- function(ptrA) {
    .Call('gpuRcuda_cpp_dnrow', PACKAGE = 'gpuRcuda', ptrA)
}

cpp_fnrow <- function(ptrA) {
    .Call('gpuRcuda_cpp_fnrow', PACKAGE = 'gpuRcuda', ptrA)
}

cpp_inrow <- function(ptrA) {
    .Call('gpuRcuda_cpp_inrow', PACKAGE = 'gpuRcuda', ptrA)
}

cpp_dgpuVec_size <- function(ptrA) {
    .Call('gpuRcuda_cpp_dgpuVec_size', PACKAGE = 'gpuRcuda', ptrA)
}

cpp_fgpuVec_size <- function(ptrA) {
    .Call('gpuRcuda_cpp_fgpuVec_size', PACKAGE = 'gpuRcuda', ptrA)
}

cpp_igpuVec_size <- function(ptrA) {
    .Call('gpuRcuda_cpp_igpuVec_size', PACKAGE = 'gpuRcuda', ptrA)
}

cpp_vienna_cudaMatrix_saxpy <- function(alpha_, ptrA_, ptrB_) {
    invisible(.Call('gpuRcuda_cpp_vienna_cudaMatrix_saxpy', PACKAGE = 'gpuRcuda', alpha_, ptrA_, ptrB_))
}

cpp_vienna_cudaMatrix_daxpy <- function(alpha_, ptrA_, ptrB_) {
    invisible(.Call('gpuRcuda_cpp_vienna_cudaMatrix_daxpy', PACKAGE = 'gpuRcuda', alpha_, ptrA_, ptrB_))
}

cpp_vienna_cudaMatrix_sColMean <- function(ptrA_, ptrC_) {
    invisible(.Call('gpuRcuda_cpp_vienna_cudaMatrix_sColMean', PACKAGE = 'gpuRcuda', ptrA_, ptrC_))
}

cpp_vienna_cudaMatrix_dColMean <- function(ptrA_, ptrC_) {
    invisible(.Call('gpuRcuda_cpp_vienna_cudaMatrix_dColMean', PACKAGE = 'gpuRcuda', ptrA_, ptrC_))
}

cpp_vienna_cudaMatrix_scolsum <- function(ptrA_, ptrC_) {
    invisible(.Call('gpuRcuda_cpp_vienna_cudaMatrix_scolsum', PACKAGE = 'gpuRcuda', ptrA_, ptrC_))
}

cpp_vienna_cudaMatrix_dcolsum <- function(ptrA_, ptrC_) {
    invisible(.Call('gpuRcuda_cpp_vienna_cudaMatrix_dcolsum', PACKAGE = 'gpuRcuda', ptrA_, ptrC_))
}

cpp_vienna_cudaMatrix_sgemm <- function(ptrA_, ptrB_, ptrC_) {
    invisible(.Call('gpuRcuda_cpp_vienna_cudaMatrix_sgemm', PACKAGE = 'gpuRcuda', ptrA_, ptrB_, ptrC_))
}

cpp_vienna_cudaMatrix_dgemm <- function(ptrA_, ptrB_, ptrC_) {
    invisible(.Call('gpuRcuda_cpp_vienna_cudaMatrix_dgemm', PACKAGE = 'gpuRcuda', ptrA_, ptrB_, ptrC_))
}

cpp_vienna_cudaMatrix_sRowMean <- function(ptrA_, ptrC_) {
    invisible(.Call('gpuRcuda_cpp_vienna_cudaMatrix_sRowMean', PACKAGE = 'gpuRcuda', ptrA_, ptrC_))
}

cpp_vienna_cudaMatrix_dRowMean <- function(ptrA_, ptrC_) {
    invisible(.Call('gpuRcuda_cpp_vienna_cudaMatrix_dRowMean', PACKAGE = 'gpuRcuda', ptrA_, ptrC_))
}

cpp_vienna_cudaMatrix_sRowSum <- function(ptrA_, ptrC_) {
    invisible(.Call('gpuRcuda_cpp_vienna_cudaMatrix_sRowSum', PACKAGE = 'gpuRcuda', ptrA_, ptrC_))
}

cpp_vienna_cudaMatrix_dRowSum <- function(ptrA_, ptrC_) {
    invisible(.Call('gpuRcuda_cpp_vienna_cudaMatrix_dRowSum', PACKAGE = 'gpuRcuda', ptrA_, ptrC_))
}

