# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sexpToDeviceMatrix <- function(x, nr, nc, type_flag) {
    .Call('_gpuRcuda_sexpToDeviceMatrix', PACKAGE = 'gpuRcuda', x, nr, nc, type_flag)
}

cudaMatToSEXP <- function(ptrA, x, type_flag) {
    invisible(.Call('_gpuRcuda_cudaMatToSEXP', PACKAGE = 'gpuRcuda', ptrA, x, type_flag))
}

cudaMatEmtpy <- function(nr, nc, type_flag) {
    .Call('_gpuRcuda_cudaMatEmtpy', PACKAGE = 'gpuRcuda', nr, nc, type_flag)
}

sexpToDeviceVector <- function(x, size, type_flag) {
    .Call('_gpuRcuda_sexpToDeviceVector', PACKAGE = 'gpuRcuda', x, size, type_flag)
}

cudaVecToSEXP <- function(ptrA, x, type_flag) {
    invisible(.Call('_gpuRcuda_cudaVecToSEXP', PACKAGE = 'gpuRcuda', ptrA, x, type_flag))
}

cudaVecEmpty <- function(size, type_flag) {
    .Call('_gpuRcuda_cudaVecEmpty', PACKAGE = 'gpuRcuda', size, type_flag)
}

sexpToHostMatrix <- function(x, nr, nc, type_flag) {
    .Call('_gpuRcuda_sexpToHostMatrix', PACKAGE = 'gpuRcuda', x, nr, nc, type_flag)
}

nvMatToSEXP <- function(ptrA, x, type_flag) {
    invisible(.Call('_gpuRcuda_nvMatToSEXP', PACKAGE = 'gpuRcuda', ptrA, x, type_flag))
}

nvMatEmtpy <- function(nr, nc, type_flag) {
    .Call('_gpuRcuda_nvMatEmtpy', PACKAGE = 'gpuRcuda', nr, nc, type_flag)
}

sexpToHostVector <- function(x, size, type_flag) {
    .Call('_gpuRcuda_sexpToHostVector', PACKAGE = 'gpuRcuda', x, size, type_flag)
}

nvVecToSEXP <- function(ptrA, x, type_flag) {
    invisible(.Call('_gpuRcuda_nvVecToSEXP', PACKAGE = 'gpuRcuda', ptrA, x, type_flag))
}

nvVecEmpty <- function(size, type_flag) {
    .Call('_gpuRcuda_nvVecEmpty', PACKAGE = 'gpuRcuda', size, type_flag)
}

cpp_length <- function(ptrA, type_flag) {
    .Call('_gpuRcuda_cpp_length', PACKAGE = 'gpuRcuda', ptrA, type_flag)
}

cpp_ncol <- function(ptrA, type_flag) {
    .Call('_gpuRcuda_cpp_ncol', PACKAGE = 'gpuRcuda', ptrA, type_flag)
}

cpp_nrow <- function(ptrA, type_flag) {
    .Call('_gpuRcuda_cpp_nrow', PACKAGE = 'gpuRcuda', ptrA, type_flag)
}

